os: linux
dist: xenial
git:
  depth: 1
language: go
go:
  - "1.13"
env:
  - GO111MODULE=on
before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.21.0
jobs:
  include:
    - script: make test-race
    - stage: "QA"
      name: "Linting"
      script: make lint
    - name: "Code Analysis"
      script: make ca
    - name: "Tests coverage"
      script: make coverage
    - name: "Benckmarks"
      script: make benchmark
    - stage: "Build"
      script: make build
after_success:
  - bash <(curl -s https://codecov.io/bash)

